name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-json-ctrf
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install python packages
      run: pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        export GIT_SHORT_COMMIT=$(git rev-parse --short HEAD)
        echo $GIT_SHORT_COMMIT
        pytest -vv --ctrf ./test/report.json
    
    - name: Publish Test Report
      uses: actions/github-test-reporter@v1
      with:
        report-path: './test/*.json'
        pull-request: true
        update-comment: true
        comment-tag: '${{ github.workflow }}-${{ github.job }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()
