name: Test Pull Request

on:
  pull_request_target:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: rpl-linux-runners
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ secrets.GITHUB_TOKEN }}  

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install python packages
      run: pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        export GIT_SHORT_COMMIT=$(git rev-parse --short HEAD)
        echo $GIT_SHORT_COMMIT
        pytest -vv --ctrf ./test/report.json
    
    - name: Publish Test Report
      uses: actions/github-test-reporter@v1
      with:
        report-path: './test/*.json'
        pull-request: true
        update-comment: true
        comment-tag: '${{ github.workflow }}-${{ github.job }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()
